name: Deploy to EC2

on:
  push:
    branches:
      - main  # Change to the branch you want to use for deployment

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from the repo
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up SSH key and permissions
      - name: Add SSH key
        run: |
          echo "${{ secrets.EC2_KEY_PAIR }}" > ec2-key.pem
          chmod 600 ec2-key.pem

      # Step 3: SSH into EC2 and deploy the code
      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i ec2-key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            cd /home/ubuntu/open-websockets
            git pull origin main
            app/restart_server
          EOF
